sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.version=3.10

sonar.host.url=http://localhost:9000
sonar.login=sqa_34988f7d09049b2a519ba0ef3b58b29301bb11cbas
